apiVersion: v1
kind: Secret
metadata:
  name: k8l-backend-secrets
  namespace: k8l
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "Y17UnAHFcGNpc_gaB5W4maBdEOG_cZPvPDQk9r4aq_46-vHSfX_a8bVEMUAXWHRuovg"
  MONGODB_URI: "mongodb://10.0.12.62:27017/k8l"